# Generated by Django 4.1.4 on 2022-12-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(blank=True, max_length=1000)),
                ('nom', models.CharField(blank=True, default='image', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('picture', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('taille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.taille', verbose_name='Taille')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.type', verbose_name='Type')),
            ],
        ),
    ]
