# Generated by Django 4.1.4 on 2022-12-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_taille_type_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='nom',
            field=models.CharField(blank=True, default='image', max_length=100, unique=True),
        ),
    ]
