# Generated by Django 4.1.4 on 2022-12-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pizza_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='type',
        ),
        migrations.AddField(
            model_name='pizza',
            name='type',
            field=models.ManyToManyField(to='api.type', verbose_name='Type'),
        ),
    ]
