# Generated by Django 4.1.4 on 2022-12-29 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_pizza_type_pizza_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='taille',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='type',
        ),
        migrations.AddField(
            model_name='pizza',
            name='taille',
            field=models.ManyToManyField(to='api.taille', verbose_name='Taille'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.type', verbose_name='Type'),
            preserve_default=False,
        ),
    ]
