# Generated by Django 4.1.4 on 2023-01-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_pizza_taille_remove_pizza_type_pizza_taille_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='picture',
            field=models.CharField(max_length=3000),
        ),
    ]
